CREATE TABLE `tandem_ssh_trust` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`profile_scope` text NOT NULL,
	`address` text NOT NULL,
	`port` integer NOT NULL,
	`fingerprint` text NOT NULL,
	`key_type` text NOT NULL,
	`revision` integer NOT NULL,
	`approved_at` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_ssh_data` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`user_id` text NOT NULL,
	`connection_type` text DEFAULT 'ssh' NOT NULL,
	`name` text,
	`ip` text NOT NULL,
	`port` integer NOT NULL,
	`username` text NOT NULL,
	`folder` text,
	`parent_host_id` integer,
	`tags` text,
	`pin` integer DEFAULT false NOT NULL,
	`sort_order` integer,
	`auth_type` text NOT NULL,
	`use_warpgate` integer DEFAULT false NOT NULL,
	`share_ssh_auth` integer DEFAULT false NOT NULL,
	`force_keyboard_interactive` text,
	`password` text,
	`key` text(8192),
	`key_password` text,
	`key_type` text,
	`sudo_password` text,
	`autostart_password` text,
	`autostart_key` text(8192),
	`autostart_key_password` text,
	`credential_id` integer,
	`override_credential_username` integer,
	`vault_profile_id` integer,
	`enable_terminal` integer DEFAULT true NOT NULL,
	`enable_session_logging` integer DEFAULT false NOT NULL,
	`allow_session_sharing` integer DEFAULT true NOT NULL,
	`enable_command_history` integer DEFAULT true NOT NULL,
	`enable_tunnel` integer DEFAULT true NOT NULL,
	`tunnel_connections` text,
	`jump_hosts` text,
	`enable_file_manager` integer DEFAULT true NOT NULL,
	`scp_legacy` integer DEFAULT false NOT NULL,
	`enable_docker` integer DEFAULT false NOT NULL,
	`enable_tmux_monitor` integer DEFAULT false NOT NULL,
	`enable_terminal_toolbar` integer DEFAULT true NOT NULL,
	`show_terminal_in_sidebar` integer DEFAULT true NOT NULL,
	`show_file_manager_in_sidebar` integer DEFAULT false NOT NULL,
	`show_tunnel_in_sidebar` integer DEFAULT false NOT NULL,
	`show_docker_in_sidebar` integer DEFAULT false NOT NULL,
	`show_server_stats_in_sidebar` integer DEFAULT false NOT NULL,
	`default_path` text,
	`stats_config` text,
	`docker_config` text,
	`enable_proxmox` integer DEFAULT false NOT NULL,
	`proxmox_config` text,
	`enable_proxmox_stats` integer DEFAULT false NOT NULL,
	`proxmox_stats_config` text,
	`terminal_config` text,
	`quick_actions` text,
	`notes` text,
	`enable_ssh` integer DEFAULT true NOT NULL,
	`enable_rdp` integer DEFAULT false NOT NULL,
	`enable_vnc` integer DEFAULT false NOT NULL,
	`enable_telnet` integer DEFAULT false NOT NULL,
	`ssh_port` integer DEFAULT 22,
	`rdp_port` integer DEFAULT 3389,
	`vnc_port` integer DEFAULT 5900,
	`telnet_port` integer DEFAULT 23,
	`rdp_credential_id` integer,
	`rdp_user` text,
	`rdp_password` text,
	`rdp_domain` text,
	`rdp_security` text,
	`rdp_ignore_cert` integer DEFAULT false,
	`vnc_credential_id` integer,
	`vnc_password` text,
	`vnc_user` text,
	`telnet_user` text,
	`telnet_password` text,
	`telnet_credential_id` integer,
	`rdp_auth_type` text,
	`vnc_auth_type` text,
	`telnet_auth_type` text,
	`domain` text,
	`security` text,
	`ignore_cert` integer DEFAULT false,
	`guacamole_config` text,
	`use_socks5` integer,
	`socks5_host` text,
	`socks5_port` integer,
	`socks5_username` text,
	`socks5_password` text,
	`socks5_proxy_chain` text,
	`connection_origin` text,
	`mac_address` text,
	`wol_broadcast_address` text,
	`port_knock_sequence` text,
	`host_key_fingerprint` text,
	`host_key_type` text,
	`host_key_algorithm` text DEFAULT 'sha256',
	`host_key_first_seen` text,
	`host_key_last_verified` text,
	`host_key_changed_count` integer DEFAULT 0,
	`sync_id` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`parent_host_id`) REFERENCES `ssh_data`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`credential_id`) REFERENCES `ssh_credentials`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`vault_profile_id`) REFERENCES `vault_profiles`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`rdp_credential_id`) REFERENCES `ssh_credentials`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`vnc_credential_id`) REFERENCES `ssh_credentials`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`telnet_credential_id`) REFERENCES `ssh_credentials`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
INSERT INTO `__new_ssh_data`("id", "user_id", "connection_type", "name", "ip", "port", "username", "folder", "parent_host_id", "tags", "pin", "sort_order", "auth_type", "use_warpgate", "share_ssh_auth", "force_keyboard_interactive", "password", "key", "key_password", "key_type", "sudo_password", "autostart_password", "autostart_key", "autostart_key_password", "credential_id", "override_credential_username", "vault_profile_id", "enable_terminal", "enable_session_logging", "allow_session_sharing", "enable_command_history", "enable_tunnel", "tunnel_connections", "jump_hosts", "enable_file_manager", "scp_legacy", "enable_docker", "enable_tmux_monitor", "enable_terminal_toolbar", "show_terminal_in_sidebar", "show_file_manager_in_sidebar", "show_tunnel_in_sidebar", "show_docker_in_sidebar", "show_server_stats_in_sidebar", "default_path", "stats_config", "docker_config", "enable_proxmox", "proxmox_config", "enable_proxmox_stats", "proxmox_stats_config", "terminal_config", "quick_actions", "notes", "enable_ssh", "enable_rdp", "enable_vnc", "enable_telnet", "ssh_port", "rdp_port", "vnc_port", "telnet_port", "rdp_credential_id", "rdp_user", "rdp_password", "rdp_domain", "rdp_security", "rdp_ignore_cert", "vnc_credential_id", "vnc_password", "vnc_user", "telnet_user", "telnet_password", "telnet_credential_id", "rdp_auth_type", "vnc_auth_type", "telnet_auth_type", "domain", "security", "ignore_cert", "guacamole_config", "use_socks5", "socks5_host", "socks5_port", "socks5_username", "socks5_password", "socks5_proxy_chain", "connection_origin", "mac_address", "wol_broadcast_address", "port_knock_sequence", "host_key_fingerprint", "host_key_type", "host_key_algorithm", "host_key_first_seen", "host_key_last_verified", "host_key_changed_count", "sync_id", "created_at", "updated_at") SELECT "id", "user_id", "connection_type", "name", "ip", "port", "username", "folder", "parent_host_id", "tags", "pin", "sort_order", "auth_type", "use_warpgate", "share_ssh_auth", "force_keyboard_interactive", "password", "key", "key_password", "key_type", "sudo_password", "autostart_password", "autostart_key", "autostart_key_password", "credential_id", "override_credential_username", "vault_profile_id", "enable_terminal", "enable_session_logging", "allow_session_sharing", "enable_command_history", "enable_tunnel", "tunnel_connections", "jump_hosts", "enable_file_manager", "scp_legacy", "enable_docker", "enable_tmux_monitor", "enable_terminal_toolbar", "show_terminal_in_sidebar", "show_file_manager_in_sidebar", "show_tunnel_in_sidebar", "show_docker_in_sidebar", "show_server_stats_in_sidebar", "default_path", "stats_config", "docker_config", "enable_proxmox", "proxmox_config", "enable_proxmox_stats", "proxmox_stats_config", "terminal_config", "quick_actions", "notes", "enable_ssh", "enable_rdp", "enable_vnc", "enable_telnet", "ssh_port", "rdp_port", "vnc_port", "telnet_port", "rdp_credential_id", "rdp_user", "rdp_password", "rdp_domain", "rdp_security", "rdp_ignore_cert", "vnc_credential_id", "vnc_password", "vnc_user", "telnet_user", "telnet_password", "telnet_credential_id", "rdp_auth_type", "vnc_auth_type", "telnet_auth_type", "domain", "security", "ignore_cert", "guacamole_config", "use_socks5", "socks5_host", "socks5_port", "socks5_username", "socks5_password", "socks5_proxy_chain", "connection_origin", "mac_address", "wol_broadcast_address", "port_knock_sequence", "host_key_fingerprint", "host_key_type", "host_key_algorithm", "host_key_first_seen", "host_key_last_verified", "host_key_changed_count", "sync_id", "created_at", "updated_at" FROM `ssh_data`;--> statement-breakpoint
DROP TABLE `ssh_data`;--> statement-breakpoint
ALTER TABLE `__new_ssh_data` RENAME TO `ssh_data`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `ssh_data_sync_id_unique` ON `ssh_data` (`sync_id`);--> statement-breakpoint
CREATE INDEX `idx_ssh_data_user_id` ON `ssh_data` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_ssh_data_parent_host` ON `ssh_data` (`parent_host_id`);--> statement-breakpoint
CREATE INDEX `idx_ssh_data_credential` ON `ssh_data` (`credential_id`);